name: emergency_app
description: Emergency caller agent mobile app
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.2.1
  permission_handler: ^12.0.1
  geolocator: ^14.0.2
  http: ^1.1.0
  sqflite: ^2.3.0
  shared_preferences: ^2.0.13
  provider: ^6.0.5
  fl_chart: ^1.1.1
  dio: ^5.9.0
  flutter_secure_storage: ^9.2.4
  #futuristic_home_dashboard: ^0.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
